POST http://localhost:4000/boards/{{boardId}}/tasks
Authorization: Bearer {{token}}
Content-Type: application/json
Origin: {{host}}
Referer: {{host}}/
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

{
  "title": "Autotest task",
  "order": 0,
  "description": "Lorem ipsum",
  "userId": null,
  "boardId": null,
  "columnId": null
}

> {%
 client.global.set("taskId", response.body.id); //userId - updateById variable from response
 %}

###

GET http://localhost:4000/boards/{{boardId}}/tasks
Authorization: Bearer {{token}}
Content-Type: application/json
Origin: {{host}}
Referer: {{host}}/
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

###


GET http://localhost:4000/boards/{{boardId}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
Content-Type: application/json
Origin: {{host}}
Referer: {{host}}/
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

###

PUT http://localhost:4000/boards/{{boardId}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
Content-Type: application/json
Origin: {{host}}
Referer: {{host}}/
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

{
  "name": "Coder_1"
}
###

DELETE http://localhost:4000/boards/{{boardId}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
Content-Type: application/json
Origin: {{host}}
Referer: {{host}}/
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

###

